#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "############## TESTING   ###########"
echo $DOCKER_USERNAME
echo $DOCKER_PASSWORD
echo "############## TESTING   ###########"
docker push cybercuffs/woolly